microservice:
  replicas: 3

env:
  APP_ENV: prod

ingress:
  hosts:
    - host: employee-grade.com
      paths:
        - path: /api
          pathType: Prefix
        - path: /
          pathType: Prefix

autoscaling:
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80