microservice:
  name: employee-grade-portal
  namespace: grade-portal
  replicas: 2

frontend:
  image: employee-grade-frontend:1.0
  port: 5001
  service:
    type: ClusterIP
    port: 5001
    targetPort: 5001

backend:
  image: employee-grade-api:1.0
  port: 3000
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000

env:
  APP_ENV: dev

ingress:
  enabled: true
  className: traefik

autoscaling:
  enabled: true