apiVersion: v1

kind: Service

metadata:
  name: {{ .Values.microservice.name }}-backend
  namespace: {{ .Values.microservice.namespace }}

spec:
  type: {{ .Values.backend.service.type }}

  selector:
    app: {{ .Values.microservice.name }}-backend

  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP